on: push
+ name: Deploy Code
jobs:
+ deploy-code:
    name: Deploy
    runs-on: ubuntu-latest
steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
+        server-dir: vausimmons.slccwebdev.com/
         server: vausimmons.slccwebdev.com
         username: ${{ secrets.ftp_vausimmons }}
         password: ${{ secrets.ftp_VaughnSimmons2020 }}sh
        
        
